web_app/jobs/urls.py
from django.urls import path
from . import views


app_name = "jobs"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.JobSearch.as_view(), name="search"),
    path("job/<int:job_id>/", views.job_detail, name="job_detail"),
]

web_app/skills/urls.py
from django.urls import path
from . import views


app_name = "skills"
urlpatterns = [
    path("", views.index, name="skill_list"),
    path("skill/<int:skill_id>/", views.detail, name="detail"),
]

web_app/web_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("jobs/", include("jobs.urls")),
    path("skills/", include("skills.urls")),
    path("companies/", include("companies.urls")),
    path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
]

web_app/skills/models.py
"""
Contains skills app models.

Content: Skill model.
"""
from django.db import models


class Skill(models.Model):
    """
    Skills required for jobs.

    Skill model is used in jobs and user apps.

    Attributes:
        skill_name: models.CharField Name of the skill
        skill_description: models.CharField Long description of the skill
    """
    skill_name = models.CharField(
        "skill title", max_length=50, unique=True
    )
    skill_description = models.TextField("skill description", blank=True, null=True)

    class Meta:
        ordering = ["skill_name"]
        verbose_name = "skill"
        verbose_name_plural = "skills"

    def __str__(self):
        return self.skill_name

web_app/skills/views.py
"""
Views for pages related to skills app.

Contains views:
    index - List of all skills.
    detail - Details for a particular skill.
"""
from django.shortcuts import get_object_or_404, render
from .models import Skill


def index(request):
    """
    List of all skills.

    Skills ordered by skill name.

    Args:
        request: HttpRequest request from a client.

    Returns:
        HttpResponse List of all skills rendered with
            skills/index.html template.
    """
    skill_list = Skill.objects.order_by("skill_name")
    context = {"skill_list": skill_list, }
    return render(request, "skills/index.html", context)


def detail(request, skill_id):
    """
    Details for a particular skill.

    Skill with all it's fields.

    Args:
        request: HttpRequest request from a client.
        skill_id: int id value for a particular skill.

    Returns:
        HttpResponse Skill details rendered with
            skills/details.html template.
    """
    skill_details = get_object_or_404(Skill, pk=skill_id)
    context = {"skill_details": skill_details, }
    return render(request, "skills/details.html", context)

web_app/skills/templates/skills/details.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Skill details</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
        {% if skill_details %}
            <h2>{{ skill_details.skill_name }}</h2>
        {% else %}
            <div><span>Skill does not exist!</span></div>
        {% endif %}
    </body>
</html>

web_app/skills/templates/skills/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Skill list</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
        {% if skill_list %}    
            <ul>
            {% for skill in skill_list %}
            <li><a href="{% url 'skills:detail' skill.id %}">{{ skill.skill_name }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No skills are available.</p>
        {% endif %}
            
    </body>
</html>